name: Upload Python Package

on:
  push:
    branches: master

jobs:
  deploy:

    runs-on: runner1

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to host1
      run: |
        cp * /home/creston
