name: Upload Python Package

on:
  push:
    branches: master

jobs:
  deploy1:

    runs-on: runner1

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to host1
      run: |
        cp * /home/crestron

  deploy2:

    runs-on: runner2

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to host2
      run: |
        cp * /home/crestron
